version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_DB: facilitaJuridico-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - facilitajuridico-network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    networks:
      - facilitajuridico-network

networks:
  facilitajuridico-network:
